"""Add project table

Revision ID: 2bf5d035b7f1
Revises: a1b71c4fdab9
Create Date: 2025-11-18 13:53:36.321290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf5d035b7f1'
down_revision: Union[str, Sequence[str], None] = 'a1b71c4fdab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'todos', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
